### ISSUE TITLE
I want to know about the audio value range [-1,1]

### ISSUE THREAD

**Issue by avis-ma** [SheldonTsui/SepStereo_ECCV2020#1]
Hello, I am also a researcher in the direction of sound source separation. I have benefited a lot from seeing your work.
But I have some questions about sound processing.
1) Why should the raw audios' values be limited between -1 and 1?
2) I did some verification. There is a difference between performing STFT after sound mixing, and performing STFT first and then mixing on the spectrum. STFT(audio1+audio2)≠(STFT(audio1) + STFT(audio2)) 
How can this be explained?
Looking forward to your reply.

**Comment by SheldonTsui** [comment]
@avis-ma Clipping the values between -1 and 1 is a widely used pre-processing step in this field. It will make the network easier to train. For the second question, I have proved it theoretically in the supplement material. Besides, I have verified it in the experiments. Please try it more carefully.
